version: "3.9"
services:
  db-showcase:
    container_name: db-showcase
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  
  rabbit-mq-showcase:
    container_name: rabbit-mq-showcase
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
        
  redis-showcase:
    container_name: redis-showcase
    image: "redis:6-alpine"
    ports:
      - "6379:6379"